BookStore/Controllers/CartController.cs
using BookStore.Data;
using BookStore.Models;
using Microsoft.AspNetCore.Mvc;

namespace BookStore.Controllers
{
    public class CartController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CartController(ApplicationDbContext context)
        {
            _context = context;
        }
        public IActionResult MakeCart(int id, int quantity, string customerName, int price)
        {
            TempData["ok"] = "Order successfully !";
            var order = new Cart();
            order.Status = -1;
            order.Price = price;
            order.OrderQuantity = quantity;
            order.ProductId = id;
            order.Customer = customerName;
            order.OrderName = _context.Product.Find(id).Title;
            order.OrderPrice = (_context.Product.Find(id).Price) * quantity;

            _context.Carts.Add(order);
            _context.SaveChanges();
            return View(order);
        }

        public IActionResult CancelCart(int id)
        {
            var order = _context.Carts.Find(id);
            _context.Carts.Remove(order);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
    }
}

BookStore/Controllers/ClientController.cs
using BookStore.Data;
using BookStore.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;
using static Microsoft.Extensions.Logging.EventSource.LoggingEventSource;

namespace BookStore.Controllers
{
    public class ClientController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ClientController(ApplicationDbContext context)
        {
            _context = context;
        }

        [Route("/")]
        // GET: Products
        public async Task<IActionResult> Index()
        {
            return View(await _context.Product.ToListAsync());
        }

        public async Task<IActionResult> Details(int id)
        {
            var books = _context.Product.Find(id);
            return View(books);
        }

        [HttpPost]
        public async Task<IActionResult> Search(string keyword)
        {
            var books = _context.Product.Where(x=>x.Title.Contains(keyword)).ToList();
            if (!String.IsNullOrEmpty(keyword))
            {
                @TempData["Message"] = "No book found";
            }
            return View("Index", books);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

BookStore/Views/Client/Details.cshtml
@model BookStore.Models.Product
@{
    ViewData["Title"] = "Detail Page";
}

<style>
    #img > img {
        width: 650px;
        max-width: 100%;
        height: 500px;
        -webkit-backface-visibility: hidden;
    }

    body {
        background: #f5f5f5;
    }

    .rounded {
        border-radius: 5px !important;
    }

    .product-title {
        margin: 15px 0;
        background-color: #fff;
        padding: 30px 40px;
        border-radius: 5px;
    }

    .product-infor {
        margin: 15px 0;
        background-color: #fff;
        padding: 30px 40px;
        border-radius: 5px;
    }

        .product-infor p {
            margin-bottom: 15px;
            padding-bottom: 15px;
            border-bottom: 1px solid #d5dadb;
        }

    .quantity {
        width: 120px;
    }

    .related-product h2 {
        margin: 30px;
        text-align: center;
    }

    .card-deck {
        margin: 15px 0;
        background-color: #fff;
        padding: 30px 40px;
        border-radius: 5px;
    }
</style>

<div class="container mt-5">
    <div class="row">
        <div class="col-md-5" style="margin: 10px" id="img">
            <img src ="~/images/@Model.Image" />
        </div>

        <div class="col-md-6" style="margin: 10px">
            <div class="product-title mt-0">
                <h2>@Model.Title</h2>
                <p class="md-0 font-weight-lighter">Description: @Model.Description</p>
            </div>

            <div class="product-infor">
                <p>
                    <b>Author:</b>
                    @Model.Author
                </p>
                <p><b>Price:</b> @Model.Price$</p>
                <div class="form-group">
                    <label>
                        <b>Quantity:</b><input type="number" placeholder="1" class="form-control quantity">
                    </label>
                </div>
                <form method="post" asp-controller="Cart" asp-action="MakeCart" asp-route-id="@Model.Id" asp-route-price="@Model.Price"
                      asp-route-customerName="@User.Identity.Name">
                    <div class="text-center row" style="margin-left:520px">
                        <div>
                            <input type="hidden" name="book" />
                        </div>
                        <div class="col-md-2 mr-5">
                            <input type="number" name="quantity" min="1" max="@Model.Quantity" value="1" class="form-control" style="width: 70px">
                        </div>
                        <div class="col-md-2">
                            <input class="btn btn-success" type="submit" value="Order" style="width:100px">
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

BookStore/Views/Client/Index.cshtml
@model IEnumerable<BookStore.Models.Product>
@{
    ViewData["Title"] = "Home Page";
}

    <!-- Section-->
    <section class="py-5">
        <div class="container px-4 px-lg-5 mt-5">
            <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
                @foreach (var item in Model)
                {
                    <div class="col mb-5">
                        <div class="card h-100">
                            <!-- Product image-->
                            <img class="card-img-top" src="~/images/@item.Image" alt="..." />
                            <!-- Product details-->
                            <div class="card-body p-4">
                                <div class="text-center">
                                    <!-- Product name-->
                                    <h5 class="fw-bolder">@item.Title</h5>
                                    <!-- Product price-->
                            @item.Price
                                </div>
                            </div>
                            <!-- Product actions-->
                            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                <div class="text-center"><a class="btn btn-outline-dark mt-auto" asp-controller="Client" asp-action="Details" asp-route-id="@item.Id">View Details</a></div>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </section>




    